"""add test col to posts

Revision ID: 8c7ab4931f6c
Revises: 1ebe63b4036f
Create Date: 2026-03-27 20:57:55.456119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c7ab4931f6c'
down_revision: Union[str, Sequence[str], None] = '1ebe63b4036f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('test_col', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'test_col')
    # ### end Alembic commands ###
